### ISSUE TITLE
Vertical alignment of Inventory HBox Container isn't centered

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#10]
The Menu, Notepad and Reveal node are vertically centered, but the Inventory HBox Container isn't.
In case the inventory size is too big, the icons are not vertically aligned.
Here's a small screenshot (with an inventory size too big to highlight the effect). The 'N' icon represents the notepad.
![inv](https://user-images.githubusercontent.com/67240202/116000253-bfe2a300-a5ef-11eb-9a1e-3eb88f1e31fd.png)

Proposal: Change size flag of node Inventory within the InventoryPanel from 'Vertical -> Fill' to 'Vertical -> Shrink Center' to also vertically center the Inventory HBox.
![inv2](https://user-images.githubusercontent.com/67240202/116000352-22d43a00-a5f0-11eb-8d74-7ab5d3c4a455.png)

**Comment by dploeger** [comment]
Thanks! Especially for the proposal as well!
