### ISSUE TITLE
Issue with latest commit - _overridden_cursors array is initial in reset function

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#11]
After applying the latest commit I've received a runtime error in function reset() in cursors.gd when changing a scene because the _overridden_cursors array is initial.

I've applied a workaround by first checking whether the 'type' exists in the _overridden array:

`func reset(type):`

	var target_mouse_position = null
	if _overridden_cursors.has(type):
		target_mouse_position = get_viewport().get_mouse_position() - \
				_overridden_cursors[type]['hotspot'] + \
				_default_cursors[type].cursor_hotspot
		_overridden_cursors.erase(type)
		
	Speedy.set_custom_mouse_cursor(

**Comment by dploeger** [comment]
Yeah, @MikaelNyqvist found that one as well. We already fixed it in deep-entertainment/egoventure-example-game@960b01e982958b1b62a0906373b4386453866a76

**Comment by dploeger** [comment]
Fixed here as well. Be aware of a change in the cursors list over in cursor.gd. That could be a breaking change for you.
