### ISSUE TITLE
[Proposal] Positions/margins in four_side_room.tscn don't fit to non-WQHD resolution

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#2]
The positions and margins in four_side_room.tscn are optimized for WQHD resolution.
When using the template for a non-WQHD game it is required to overwrite the template.
Would it be possible to replace the 'hard coded' coordinates by parameters to avoid modifications?
Thanks,  Thomas

**Comment by dploeger** [comment]
I think we can use the project's resolutions settings.

**Comment by dploeger** [comment]
Hm. I just checked out the code again, and it is actually using that:

https://github.com/deep-entertainment/egoventure-game-template/blob/main/addons/egoventure/nodes/four_side_room.gd#L51

Doesn't it work correctly if you change the project resolution?

**Comment by ThmsKnz** [comment]
The .gd script is fine when changing the project resolution, I was referring to the coordinates and parameters maintained in the .tscn file:
[https://github.com/deep-entertainment/egoventure-game-template/blob/main/addons/egoventure/nodes/four_side_room.tscn](url) 
for example: `[node name="Right" type="TextureButton" parent="Camera"]
margin_left = 2140.0
margin_top = 132.0
margin_right = 2568.0
margin_bottom = 1452.0 ...`
I'm not sure whether Godot allows to set them dynamically. (I'm still a Godot newbie so apologies if this is not supported :-)

**Comment by dploeger** [comment]
Ohhh! The navigation hotspots. Yes, good catch!
