### ISSUE TITLE
[Proposal] Add boolean function 'has_item' to Inventory class

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#3]
Could you add a boolean function to the Inventory class which allows to check whether an item is currently in the inventory.
`func has_item(item: InventoryItem) -> bool:`
This would reduce the need to keep an additional status variable for every item taken.
Thanks,  Thomas

**Comment by dploeger** [comment]
Done. Thanks for the suggestion.
