### ISSUE TITLE
[Proposal] Add function 'is_effect_playing() -> bool:' to boombox.gd

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#4]
I would like to wait for the end of an effect and it would help to be able to query whether the effect is still being.
It would be a similar function like is_music_playing().
Thanks,  Thomas

**Comment by dploeger** [comment]
Do you need the function or an event when the effect stopped playing? So you could use `yield(Inventory, "effect_finished")` (or something) to wait for the effect.

**Comment by ThmsKnz** [comment]
You are right, an event would be even better.

**Comment by dploeger** [comment]
Done. Thanks for the suggestion.
