### ISSUE TITLE
Parrot voice ressource location doesn't support subfolders

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#5]
I've structured the dialogs and voices in subfolders:

Example:
res://dialogs/house/dialog1.tres
res://voices/house/dialog1-0.ogg

but in parrot_dialog.gd the subfolder house is not taken into consideration when looking for the voice file:
var voice_sound = load( "%s/%s-%s.%s" % [ voices_path, _current_dialog.id, _current_line, voices_ext]

So it searches for res://voices/dialog1-0.ogg instead of res://voices/house/dialog1-0.ogg

**Comment by dploeger** [comment]
The _right_ repository would've been deep-entertainment/parrot, but this works just as well. 😊

As for the issue: I'll check it out.
