### ISSUE TITLE
Cursor is 'jumping' when moving it after scene change

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure-game-template#8]
This can be verified in Carol Refurbished as well.
Reason is that the hotspot position is not taken into account in EgoVenture.check_cursor().
It is currently only updating the shape but does not align the $Cursor of the Speedy scene.
When the first InputEventMouseMotion is processed this gets 'corrected' and the cursor 'jumps' to the correct position.

I fixed this locally by setting the cursor position taking the hotspot position into account in Speedy.set_shape()

func set_shape(shape: int):

	if not is_touch:
		current_shape = shape
		current_hotspot = hotspots[shape]
		$Cursor.texture = textures[current_shape]
		$Cursor.position = get_viewport().get_mouse_position() - current_hotspot  #this line has been added

**Comment by dploeger** [comment]
Can you give an example in the example game, where this is visible? We seem to have missed it.

**Comment by ThmsKnz** [comment]
Sure, you can see it scene transitions where cursor shapes change are having different hotspots.
You don't see it that often because most of the cursors in Carol Refurbished have the same hotspot location (32,32).

How to reproduce: When navigating in man03.tscn to the right (to barn/flowers) and you position the cursor near the bottom the cursor changes from eye (hotspot: 48,32) to down (hotspot: 42,42).
Click the mouse (without moving it).
When you then move the cursor after the click, the cursor image jumps by some pixels (=the difference in the hotspots).
To make it more visible you could simply change the hotspot from the eye to in configuration.tres to (0,0).
Then the cursor jumps after the transition by 42 pixels in both directions which is easier to spot :-)
